# Generated by Django 5.2.12 on 2026-04-02 08:21

import autoslug.fields
import courses.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_category_slug_alter_course_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', slugify=courses.models.custom_slugify, unique=True),
        ),
    ]
