# Generated by Django 5.2.12 on 2026-04-03 16:24

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_lesson_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(storage=courses.models.ChunkedVideoCloudinaryStorage(), upload_to='courses/videos/'),
        ),
    ]
